### ISSUE TITLE
May make sense to merge with https://github.com/kaitai-io/kaitai_struct_formats/pull/302/

### ISSUE THREAD

**Issue by KOLANICH** [CruelKernel/samsung_pit#1]

**Comment by evdenis** [comment]
https://github.com/kaitai-io/kaitai_struct_formats/pull/418
https://github.com/kaitai-io/kaitai_struct_formats/pull/417
https://github.com/kaitai-io/kaitai_struct_formats/pull/302
Kaitai developers are not really interested.
